# Pandas

The `numpy` module is excellent for numerical computations, but to handle missing data or arrays with mixed types takes more work. The `pandas` module is currently the most widely used tool for data manipulation, providing high-performance, easy-to-use data structures and advanced data analysis tools.

In particular `pandas` features:

* A fast and efficient "DataFrame" object for data manipulation with integrated indexing;
* Tools for reading and writing data between in-memory data structures and different formats (CSV, Excel, SQL, HDF5);
* Intelligent data alignment and integrated handling of missing data;
* Intelligent label-based slicing, fancy indexing, and subsetting of large data sets;
* Aggregating or transforming data with a powerful "group-by" engine; 
* High performance merging and joining of data sets;
* Hierarchical axis indexing provides an intuitive way of working with high-dimensional data in a lower-dimensional data structure;
* Time series-functionalities;
* Highly optimized for performance, with critical code paths written in Cython or C.

In [13]:
import pandas as pd
import numpy as np

## Series

Series are completely equivalent to 1D array but with axis labels and the possibility to store heterogeneous elements. Of paramount importance are the time-series, used to define time evolutions of a phenomenon.

In [16]:
from string import ascii_lowercase as letters

# Creating a series, accessing indexes, values and values by their index 
xs = pd.Series(np.arange(10)*0.5, index=tuple(letters[:10]))
print ("xs:", xs,'\n')
print ("xs indexes:",xs.index,'\n')
# Values of the Series are actually a numpy array
print ("xs values:", xs.values, type(xs.values),'\n')
print (xs['f'], xs.f, xs.h, '\n')
print (xs[['d', 'f', 'h']], '\n')
print (type(xs[['d', 'f', 'h']]), '\n')

xs: a    0.0
b    0.5
c    1.0
d    1.5
e    2.0
f    2.5
g    3.0
h    3.5
i    4.0
j    4.5
dtype: float64

xs indexes: Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

xs values: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5] <class 'numpy.ndarray'>

2.5 2.5 3.5

d    1.5
f    2.5
h    3.5
dtype: float64

<class 'pandas.core.series.Series'>

In [18]:
# Extracting elements and operations: same as numpy array
print (xs[:3],'\n')
print (xs[7:], '\n')
print (xs[::3], '\n')
print (xs[xs>3], '\n')
print (np.exp(xs), '\n')
print (np.mean(xs), np.std(xs), '\n')

a    0.0
b    0.5
c    1.0
dtype: float64

h    3.5
i    4.0
j    4.5
dtype: float64

a    0.0
d    1.5
g    3.0
j    4.5
dtype: float64

h    3.5
i    4.0
j    4.5
dtype: float64

a     1.000000
b     1.648721
c     2.718282
d     4.481689
e     7.389056
f    12.182494
g    20.085537
h    33.115452
i    54.598150
j    90.017131
dtype: float64

2.25 1.4361406616345072

In [20]:
# Series can be created from python dictionary too.
# Not that the elements can be whatever!
d = {'b' : 1, 'a' : 'cat', 'c' : [2,3]}
pd.Series(d)

b         1
a       cat
c    [2, 3]
dtype: object

A key difference between Series and ndarray is that operations between Series automatically align the data based on label. Thus, you can write computations without considering whether the Series involved have the same labels.

In [23]:
s = pd.Series(np.random.randn(5), index=tuple(letters[:5]))
print(s)
s = s[1:] + s[:-1]
print(s)

a   -0.013759
b    0.386464
c   -0.773601
d   -1.253694
e   -0.475075
dtype: float64
a         NaN
b    0.772927
c   -1.547202
d   -2.507389
e         NaN
dtype: float64

### Time series

Time series are very often used to profile the behaviour of a quantity as a function of time. Pandas has a special index for that, `DatetimeIndex`, that can be created e.g. with the function `pd.data_range()`

In [26]:
# to define a date, the datetime module is very useful
import datetime as dt
date = dt.date.today()
print(date)

date = dt.datetime(2025,11,26,10,45,10,15)
print (date)

# otherwise, several notations are interpreted too
date = 'Nov 26 2025'
# or alternatively
#date = '26/11/2025 10:45:00'
print (date)

days = pd.date_range(date, periods=7, freq='D')
print (days)

seconds = pd.date_range(date, periods=3600, freq='s')
print (seconds)

2025-12-18
2025-11-26 10:45:10.000015
Nov 26 2025
DatetimeIndex(['2025-11-26', '2025-11-27', '2025-11-28', '2025-11-29',
               '2025-11-30', '2025-12-01', '2025-12-02'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2025-11-26 00:00:00', '2025-11-26 00:00:01',
               '2025-11-26 00:00:02', '2025-11-26 00:00:03',
               '2025-11-26 00:00:04', '2025-11-26 00:00:05',
               '2025-11-26 00:00:06', '2025-11-26 00:00:07',
               '2025-11-26 00:00:08', '2025-11-26 00:00:09',
               ...
               '2025-11-26 00:59:50', '2025-11-26 00:59:51',
               '2025-11-26 00:59:52', '2025-11-26 00:59:53',
               '2025-11-26 00:59:54', '2025-11-26 00:59:55',
               '2025-11-26 00:59:56', '2025-11-26 00:59:57',
               '2025-11-26 00:59:58', '2025-11-26 00:59:59'],
              dtype='datetime64[ns]', length=3600, freq='S')

To learn more about the frequency strings, please see this [link](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases)


Timestamped data is the most basic type of time series data that associates values with points in time. For pandas objects it means using the points in time.

functions like `pd.to_datetime` can be used, for instance, when reading information as string from a dataset.

Timestamp is the pandas equivalent of python’s Datetime and is interchangeable with it in most cases.

In [29]:
tstamp = pd.Timestamp(dt.datetime(2020, 11, 9))

# internally it counts the nanoseconds from January 1st 19
#tstamp = pd.Timestamp(dt.datetime(1970, 1, 1, 0, 0, 0, 1))
print(tstamp.value)

# when creating a timestamp the format can be explicitly passed
ts = pd.to_datetime('2010/11/12', format='%Y/%m/%d')
print (type(ts))
print (ts.value)
ts = pd.to_datetime('12-11-2010 00:00', format='%d-%m-%Y %H:%M')
print (ts)
print (ts.value)

1604880000000000000
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
1289520000000000000
2010-11-12 00:00:00
1289520000000000000

A standard series can be created and (range of) elements can be used as indexes

In [32]:
tseries = pd.Series(np.random.normal(10, 1, len(days)), index=days)
# Extracting elements
print (tseries[0:4], '\n')
print (tseries['2025-11-26':'2025-12-02'], '\n') # Note - includes end time

2025-11-26    11.999407
2025-11-27    10.955059
2025-11-28     8.746000
2025-11-29     8.892707
Freq: D, dtype: float64

2025-11-26    11.999407
2025-11-27    10.955059
2025-11-28     8.746000
2025-11-29     8.892707
2025-11-30     9.125253
2025-12-01     8.814173
2025-12-02     7.864041
Freq: D, dtype: float64

`pd.to_datetime` can also be used to create a `DatetimeIndex`:

In [35]:
pd.to_datetime([1, 2, 3, 4], unit='D', origin=pd.Timestamp('1980-02-03'))

DatetimeIndex(['1980-02-04', '1980-02-05', '1980-02-06', '1980-02-07'], dtype='datetime64[ns]', freq=None)

## DataFrame

A pandas DataFrame is like a simple tabular spreadsheet. For future reference (or for people already familiar with R), a pandas DataFrame is very similar to the R DataFrame.

Each column in a DataFrame is a Series object.

The element can be whatever, missing data are dealt with too (as NaN)

### DataFrame creation

A DataFrame can be created implicitly, with, e.g., a DatatimeIndex object as index:

In [39]:
entries=10
dates=pd.date_range('11/26/2025 10:45:00',freq='h', periods=entries)
df = pd.DataFrame(np.random.randn(entries,4), index=dates, columns=['A','B','C','D'])
df

                            A         B         C         D
2025-11-26 10:45:00  0.239116 -0.966592  0.885327  1.280901
2025-11-26 11:45:00 -0.305418 -0.139340 -1.229210 -0.810980
2025-11-26 12:45:00  1.542168 -0.491607  1.789527  0.368471
2025-11-26 13:45:00  1.115967 -0.788248 -0.112230  0.275856
2025-11-26 14:45:00  0.618530 -0.323549  0.759958  0.989093
2025-11-26 15:45:00  0.215378 -0.585244  0.783747  1.700376
2025-11-26 16:45:00 -0.179359  0.917760  0.513283  0.052932
2025-11-26 17:45:00  1.890598  0.506271  1.089472  0.101922
2025-11-26 18:45:00  0.369122 -0.431338 -0.416247  0.833206
2025-11-26 19:45:00 -1.189420 -0.012772  1.805392 -0.820174

or by means of a dictionary:

In [42]:
df2 = pd.DataFrame(
    { 'A' : 1.,
      'B' : pd.Timestamp('20130102'),
      'C' : pd.Series(1,index=range(4),dtype='float32'),
      'D' : np.arange(7,11),
      'E' : pd.Categorical(["test","train","test","train"]),
    }
    )
df2

# check what happens if D and E had different lenghts

     A          B    C   D      E
0  1.0 2013-01-02  1.0   7   test
1  1.0 2013-01-02  1.0   8  train
2  1.0 2013-01-02  1.0   9   test
3  1.0 2013-01-02  1.0  10  train

### Viewing Data

In [45]:
df.head(2)

                            A         B         C         D
2025-11-26 10:45:00  0.239116 -0.966592  0.885327  1.280901
2025-11-26 11:45:00 -0.305418 -0.139340 -1.229210 -0.810980

In [47]:
df.tail(4)

                            A         B         C         D
2025-11-26 16:45:00 -0.179359  0.917760  0.513283  0.052932
2025-11-26 17:45:00  1.890598  0.506271  1.089472  0.101922
2025-11-26 18:45:00  0.369122 -0.431338 -0.416247  0.833206
2025-11-26 19:45:00 -1.189420 -0.012772  1.805392 -0.820174

In [49]:
df.index

DatetimeIndex(['2025-11-26 10:45:00', '2025-11-26 11:45:00',
               '2025-11-26 12:45:00', '2025-11-26 13:45:00',
               '2025-11-26 14:45:00', '2025-11-26 15:45:00',
               '2025-11-26 16:45:00', '2025-11-26 17:45:00',
               '2025-11-26 18:45:00', '2025-11-26 19:45:00'],
              dtype='datetime64[ns]', freq='H')

In [51]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [53]:
df.values

array([[ 0.23911631, -0.96659246,  0.88532688,  1.28090123],
       [-0.30541777, -0.13934033, -1.22920989, -0.81097971],
       [ 1.54216819, -0.491607  ,  1.78952683,  0.36847078],
       [ 1.11596732, -0.78824829, -0.11222962,  0.27585643],
       [ 0.61852999, -0.32354914,  0.7599584 ,  0.98909346],
       [ 0.21537842, -0.58524429,  0.78374721,  1.70037562],
       [-0.17935863,  0.91775977,  0.51328326,  0.05293166],
       [ 1.89059757,  0.50627051,  1.08947248,  0.10192247],
       [ 0.36912216, -0.43133796, -0.41624747,  0.83320623],
       [-1.18942014, -0.01277216,  1.8053923 , -0.82017387]])

In [55]:
df.describe()

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean    0.431668  -0.231466   0.586902   0.397160
std     0.912701   0.578597   0.951031   0.828827
min    -1.189420  -0.966592  -1.229210  -0.820174
25%    -0.080674  -0.561835   0.044149   0.065179
50%     0.304119  -0.377444   0.771853   0.322164
75%     0.991608  -0.044414   1.038436   0.950122
max     1.890598   0.917760   1.805392   1.700376

In [57]:
df.T

,2025-11-26 10:45:00,2025-11-26 11:45:00,2025-11-26 12:45:00,2025-11-26 13:45:00,2025-11-26 14:45:00,2025-11-26 15:45:00,2025-11-26 16:45:00,2025-11-26 17:45:00,2025-11-26 18:45:00,2025-11-26 19:45:00
A,0.239116,-0.305418,1.542168,1.115967,0.618530,0.215378,-0.179359,1.890598,0.369122,-1.189420
B,-0.966592,-0.139340,-0.491607,-0.788248,-0.323549,-0.585244,0.917760,0.506271,-0.431338,-0.012772
C,0.885327,-1.229210,1.789527,-0.112230,0.759958,0.783747,0.513283,1.089472,-0.416247,1.805392
D,1.280901,-0.810980,0.368471,0.275856,0.989093,1.700376,0.052932,0.101922,0.833206,-0.820174

In [59]:
df.sort_index(axis=0,ascending=False)

                            A         B         C         D
2025-11-26 19:45:00 -1.189420 -0.012772  1.805392 -0.820174
2025-11-26 18:45:00  0.369122 -0.431338 -0.416247  0.833206
2025-11-26 17:45:00  1.890598  0.506271  1.089472  0.101922
2025-11-26 16:45:00 -0.179359  0.917760  0.513283  0.052932
2025-11-26 15:45:00  0.215378 -0.585244  0.783747  1.700376
2025-11-26 14:45:00  0.618530 -0.323549  0.759958  0.989093
2025-11-26 13:45:00  1.115967 -0.788248 -0.112230  0.275856
2025-11-26 12:45:00  1.542168 -0.491607  1.789527  0.368471
2025-11-26 11:45:00 -0.305418 -0.139340 -1.229210 -0.810980
2025-11-26 10:45:00  0.239116 -0.966592  0.885327  1.280901

In [61]:
df.sort_values(by="C")

                            A         B         C         D
2025-11-26 11:45:00 -0.305418 -0.139340 -1.229210 -0.810980
2025-11-26 18:45:00  0.369122 -0.431338 -0.416247  0.833206
2025-11-26 13:45:00  1.115967 -0.788248 -0.112230  0.275856
2025-11-26 16:45:00 -0.179359  0.917760  0.513283  0.052932
2025-11-26 14:45:00  0.618530 -0.323549  0.759958  0.989093
2025-11-26 15:45:00  0.215378 -0.585244  0.783747  1.700376
2025-11-26 10:45:00  0.239116 -0.966592  0.885327  1.280901
2025-11-26 17:45:00  1.890598  0.506271  1.089472  0.101922
2025-11-26 12:45:00  1.542168 -0.491607  1.789527  0.368471
2025-11-26 19:45:00 -1.189420 -0.012772  1.805392 -0.820174

## Selection

### Getting slices

The following show how to get part of the DataFrame (i.e. not just the elements)

In [64]:
## standard and safe
print (df['A'],'\n')

## equivalent but dangerous (imagine blank spaces in the name of the column..)
print (df.A)

2025-11-26 10:45:00    0.239116
2025-11-26 11:45:00   -0.305418
2025-11-26 12:45:00    1.542168
2025-11-26 13:45:00    1.115967
2025-11-26 14:45:00    0.618530
2025-11-26 15:45:00    0.215378
2025-11-26 16:45:00   -0.179359
2025-11-26 17:45:00    1.890598
2025-11-26 18:45:00    0.369122
2025-11-26 19:45:00   -1.189420
Freq: H, Name: A, dtype: float64

2025-11-26 10:45:00    0.239116
2025-11-26 11:45:00   -0.305418
2025-11-26 12:45:00    1.542168
2025-11-26 13:45:00    1.115967
2025-11-26 14:45:00    0.618530
2025-11-26 15:45:00    0.215378
2025-11-26 16:45:00   -0.179359
2025-11-26 17:45:00    1.890598
2025-11-26 18:45:00    0.369122
2025-11-26 19:45:00   -1.189420
Freq: H, Name: A, dtype: float64

In [66]:
# selecting rows by counting
print (df[0:3])

# or by index
print (df["2025-11-26 10:45:00":"2025-11-26 12:45:00"])

                            A         B         C         D
2025-11-26 10:45:00  0.239116 -0.966592  0.885327  1.280901
2025-11-26 11:45:00 -0.305418 -0.139340 -1.229210 -0.810980
2025-11-26 12:45:00  1.542168 -0.491607  1.789527  0.368471
                            A         B         C         D
2025-11-26 10:45:00  0.239116 -0.966592  0.885327  1.280901
2025-11-26 11:45:00 -0.305418 -0.139340 -1.229210 -0.810980
2025-11-26 12:45:00  1.542168 -0.491607  1.789527  0.368471

### Selection by label

In [ ]:
# getting a cross section (part of the DataFrame) using a label
df.loc[dates[0]]

In [ ]:
# selecting on a multi-axis by label:
df.loc[:,['A','B']]
#a=df.loc[:,['A','B']]

In [ ]:
# showing label slicing, both endpoints are included:
df.loc['2025-11-26 14:45:00':'2025-11-26 16:45:00',['A','B']]

In [ ]:
# getting an individual element
print (df.loc[dates[1],'A'])

# equivalently
print (df.at[dates[1],'A'])

### Selecting by position

In [ ]:
# select via the position of the passed integers:
print (df.iloc[3],'\n')

# notation similar to numpy/python
print (df.iloc[3:5,0:2])

In [ ]:
# selecting raws 1,2 and 4 for columns 0 and 2
df.iloc[[1,2,4],[0,2]]

In [ ]:
# slicing rows explicitly
print (df.iloc[1:3,:],'\n')

# slicing columns explicitly
print (df.iloc[:,1:3])

# selecting an individual element by position
print(df.iloc[1,1])

### Boolean index

Very powerful way of filtering out data with certain features. Notation is very similar to numpy arrays.

In [ ]:
# Filter by a boolean condition on the values of a single column
df[df['B'] > 0]

In [ ]:
# Selecting on the basis of boolean conditions applied to the whole DataFrame
df[df>0]

# a DataFrame with the same shape is returned, with NaN's where condition is not met

### Setting

Combination of selection and setting of values

In [ ]:
# setting values by label (same as by position)
df.at[dates[0],'A'] = 0

# setting and assigning a numpy array
df.loc[:,'D'] = np.array([5] * len(df))

# defining a brend new column
df['E'] = np.arange(len(df))*0.5

# defining a brend new column by means of a pd.Series: indexes must be the same!
df['E prime'] = pd.Series(np.arange(len(df))*2, index=df.index)

df

In [ ]:
def dcos(theta):
    theta = theta*(np.pi/180)
    return np.cos(theta)
 
df['cosine'] = pd.Series(df["E"].apply(dcos), index=df.index)
df

In [ ]:
# another example of global setting
df2=df.copy()

df2[df2>0] = -df2
df2

### Are you dealing with a Copy or a View?

In general is hard to tell..

In [ ]:
dfd = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})

# This is likely a view
subset = dfd.loc[0:1, 'a']  
subset[0] = 100  # May affect `df`

print (dfd)

# This is a copy
subset = dfd.loc[[0, 1], 'a']  
subset[0] = 200  # Does NOT affect `df`

print (dfd)

The behaviour depend on the version of Pandas and on the version of Numpy that given version of Pandas depends upon. Since Pandas 1.5 "Copy-on-Write" (CoW) is (optionally) available and as of Pandas 3.0 will be the default. 

With CoW chained assignemt will never work; in the following example, the view `dfd["a"]` and `df` itself are modified in one step. This will lead to a `ChainedAssignemntError`

In [ ]:
dfd["a"][dfd["b"] > 5] = 100
dfd

With copy on write this can be done by using `loc`

In [ ]:
dfd.loc[dfd["b"] > 5, "a"] = 200
dfd

### Dropping

N.B.: dropping doesn't act permanently on the DataFrame, i.e. to get that do :
```python
df = df.drop(....)
```

In [ ]:
# Dropping by column
df.drop(['E prime'], axis=1)

#which is equivalent to
new_df=df.drop(columns=['E prime'])
new_df

In [ ]:
# Dropping by raws
# safe and always working
df.drop(df.index[[1,2,3,4]])

In [ ]:
df

In [ ]:
# something like df.drop('index_name') 
# would work but the type of index must be specificed, 
# in particular with DatetimeIndex
df.drop(pd.to_datetime("2025-11-26 18:45:00"))

## Missing data

pandas primarily uses the value np.nan to represent missing data. It is by default not included in computations.

In [ ]:
df_wNan = df[df>-0.5]
df_wNan

In [ ]:
# dropping raws with at least a Nan
df_wNan.dropna(how='any')

In [ ]:
# getting a mask
df_wNan.isna()
#df_wNan.notna()

In [ ]:
# filling missing data
df_wNan.fillna(value=0)

Fill gaps forward or backward by propagating non-NA values forward or backward:

In [ ]:
df_wNan.fillna(method='pad')

## Operations

Here comes the most relevant advantage of DataFrame. Operations on columns are extremly fast due to several intrinsic optimizations:

* They are implemented in C/Cython via NumPy.
* Pandas processes columns as contiguous memory arrays.
* Vectorized operations eliminate the need for slow Python loops.
* Efficient memory and cache utilization boost performance.

In [70]:
# Some statistics (mean() just as an example)
# raws
print (df.mean(axis=0),'\n')
# columns
print (df.mean(axis=1),'\n')

A    0.431668
B   -0.231466
C    0.586902
D    0.397160
dtype: float64

2025-11-26 10:45:00    0.359688
2025-11-26 11:45:00   -0.621237
2025-11-26 12:45:00    0.802140
2025-11-26 13:45:00    0.122836
2025-11-26 14:45:00    0.511008
2025-11-26 15:45:00    0.528564
2025-11-26 16:45:00    0.326154
2025-11-26 17:45:00    0.897066
2025-11-26 18:45:00    0.088686
2025-11-26 19:45:00   -0.054243
Freq: H, dtype: float64

In [72]:
# global operations on columns
df.apply(np.cumsum)

                            A         B         C         D
2025-11-26 10:45:00  0.239116 -0.966592  0.885327  1.280901
2025-11-26 11:45:00 -0.066301 -1.105933 -0.343883  0.469922
2025-11-26 12:45:00  1.475867 -1.597540  1.445644  0.838392
2025-11-26 13:45:00  2.591834 -2.385788  1.333414  1.114249
2025-11-26 14:45:00  3.210364 -2.709337  2.093373  2.103342
2025-11-26 15:45:00  3.425742 -3.294582  2.877120  3.803718
2025-11-26 16:45:00  3.246384 -2.376822  3.390403  3.856649
2025-11-26 17:45:00  5.136981 -1.870551  4.479876  3.958572
2025-11-26 18:45:00  5.506104 -2.301889  4.063628  4.791778
2025-11-26 19:45:00  4.316683 -2.314661  5.869020  3.971604

In [74]:
df

                            A         B         C         D
2025-11-26 10:45:00  0.239116 -0.966592  0.885327  1.280901
2025-11-26 11:45:00 -0.305418 -0.139340 -1.229210 -0.810980
2025-11-26 12:45:00  1.542168 -0.491607  1.789527  0.368471
2025-11-26 13:45:00  1.115967 -0.788248 -0.112230  0.275856
2025-11-26 14:45:00  0.618530 -0.323549  0.759958  0.989093
2025-11-26 15:45:00  0.215378 -0.585244  0.783747  1.700376
2025-11-26 16:45:00 -0.179359  0.917760  0.513283  0.052932
2025-11-26 17:45:00  1.890598  0.506271  1.089472  0.101922
2025-11-26 18:45:00  0.369122 -0.431338 -0.416247  0.833206
2025-11-26 19:45:00 -1.189420 -0.012772  1.805392 -0.820174

In [76]:
df.apply(lambda x: x.max() - x.min())

A    3.080018
B    1.884352
C    3.034602
D    2.520549
dtype: float64

In [78]:
# syntax is as usual similar to that of numpy arrays
df['A']+df['B']

2025-11-26 10:45:00   -0.727476
2025-11-26 11:45:00   -0.444758
2025-11-26 12:45:00    1.050561
2025-11-26 13:45:00    0.327719
2025-11-26 14:45:00    0.294981
2025-11-26 15:45:00   -0.369866
2025-11-26 16:45:00    0.738401
2025-11-26 17:45:00    2.396868
2025-11-26 18:45:00   -0.062216
2025-11-26 19:45:00   -1.202192
Freq: H, dtype: float64

Let's play it hard and load (in memory) a (relatively) large dataset

In [111]:
# WARNING! link in past notebook was wrong!, (if needed) get the right file from:
#!wget https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt -P ~/data/

import urllib.request
import os



os.makedirs('data1', exist_ok=True)

url_data = 'https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt?dl=1'
urllib.request.urlretrieve(url_data, 'data1/data_000637.txt')

('data1/data_000637.txt', <http.client.HTTPMessage at 0x14d486b4110>)

Let's now do some operations among (elements of) columns

In [112]:
# the one-liner killing it all
data['timens']=data['TDC_MEAS']*25/30+data['BX_COUNTER']*25

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [ ]:
data['timens']

In [ ]:
# the old slooow way
def conversion(data):
    result=[]
    for i in range(len(data)): 
        result.append(data.loc[data.index[i],'TDC_MEAS']*25/30.+data.loc[data.index[i],'BX_COUNTER']*25)
    return result

data['timens']=conversion(data)

For tasks on extremely large datasets, libraries like [Polars](https://docs.pola.rs) or [Dask](https://www.dask.org) can offer even faster alternatives by further parallelizing or optimizing columnar operations.

## Merge

pandas provides various facilities for easily combining together Series, DataFrame, and Panel objects with various kinds of set logic for the indexes and relational algebra functionality in the case of join / merge-type operations.

### Concat

concatenation (adding rows) is straightforward

In [ ]:
rdf = pd.DataFrame(np.random.randn(10, 4))
rdf

In [ ]:
# divide it into pieaces raw-wise
pieces = [rdf[:3], rdf[3:7], rdf[7:]]
pieces

In [ ]:
# put it back together
#pd.concat(pieces)

# indexes can be ignored
pd.concat(pieces, ignore_index=True)

# in case of dimension mismatch, Nan are added where needed

In [ ]:
# appending a single row (as a Series)
s = rdf.iloc[3]
rdf = pd.concat([rdf,s.to_frame().T], ignore_index=True)
rdf

### Merge/Join

SQL like operations on table can be performed on DataFrames. This is all rather sophisticated, refer to the [doc](https://pandas.pydata.org/pandas-docs/stable/merging.html#merging) for more info/examples.

#### Merging, Inner Join (default)

Only rows with matching id values are included:

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'id': [1, 2, 3], 'name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'id': [2, 3, 4], 'age': [25, 30, 35]})

# Merge on the 'id' column
result = pd.merge(df1, df2, on='id')
print(result)

#### Merging, Left Join

A left join includes all rows from `df1` (left) and fills in `NaN` for missing matches in `df2`.

In [ ]:
result = pd.merge(df2, df1, on='id', how='left')
print(result)

#### Merging, Outer Join

An outer join includes all rows from both DataFrames, filling NaN for missing values

In [ ]:
result = pd.merge(df1, df2, on='id', how='outer')
print(result)

`join` is similar to `merge` but uses index as key and has 'Left' as default

In [ ]:
df1 = pd.DataFrame({'name': ['Alice', 'Bob', 'Charlie']}, index=[1, 2, 3])
df2 = pd.DataFrame({'age': [25, 30, 35]}, index=[2, 3, 4])

result = df1.join(df2)
print(result)

## Grouping

By “group by” we are referring to a process involving one or more of the following steps:

* Splitting the data into groups based on some criteria
* Applying a function to each group independently
* Combining the results into a data structure


Grouping is one of the most powerful and at the same time most sofisticated action you can perform with DataFrames. Mastering it is key for an effective usage of Pandas and vectorized data analysis. Reading the [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html) or going through a [tutorial](https://realpython.com/pandas-groupby/) is warmly recommended. 

Let's go through a few examples:

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'C'],
    'Values': [10, 20, 30, 40, 50, 60]
}

df = pd.DataFrame(data)

# Group by 'Category' and calculate the sum
result = df.groupby('Category').sum()
print(result)

In [ ]:
# Multiple Aggregations
result = df.groupby('Category').agg(['sum', 'mean'])
print(result)

In [ ]:
# Grouping by multiple columns
df = pd.DataFrame({'Category': ['A', 'A', 'B', 'B', 'C', 'C'],
                   'Type': ['X', 'Y', 'X', 'Y', 'X', 'Y'],
                   'Values': [10, 20, 30, 40, 50, 60]})

result = df.groupby(['Category', 'Type']).sum()
print(result)

In [ ]:
# Trasformations using groupby(): add group averages to DataFrame
df['Group_Avg'] = df.groupby('Category')['Values'].transform('mean')
print(df)

In [ ]:
# filtering
filtered = df.groupby('Category').filter(lambda x: x['Values'].sum() > 50)
print(filtered)

In [ ]:
# custom aggregation with apply()
def custom_aggregation(group):
    return pd.Series({
        'Sum': group['Values'].sum(),
        'Max': group['Values'].max(),
        'Count': group['Values'].count()
    })

result = df.groupby('Category').apply(custom_aggregation)
print(result)

In [ ]:
# splitting data into groups
grouped = df.groupby('Category')

for name, group in grouped:
    print(f"Group: {name}")
    print(group)

## Multi-indexing


Hierarchical / Multi-level indexing allows sophisticated data analysis on higher dimensional data. In essence, it enables you to store and manipulate data with an arbitrary number of dimensions in lower dimensional data structures like Series (1d) and DataFrame (2d).

In [ ]:
tuples = list(zip(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
          ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']))
multi_index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
print (multi_index,'\n')

s = pd.Series(np.random.randn(8), index=multi_index)
print (s)

In [ ]:
gdf = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                          'foo', 'bar', 'foo', 'foo'],
                    'B' : ['one', 'one', 'two', 'three',
                           'two', 'two', 'one', 'three'],
                    'C' : np.random.randn(8),
                    'D' : np.random.randn(8)})
gdf

# it enables further features of the groupby method,
# e.g. when group-by by multiple columns
gdf.groupby(['A','B']).sum()

In [ ]:
# stack() method “compresses” a level in the DataFrame’s columns
gdf.groupby(['A','B']).sum().stack()

## Plotting

Just a preview, more on the next lab class!

In [ ]:
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts.cumsum().plot()

In [ ]:
import matplotlib.pyplot as plt

pdf=pd.DataFrame(np.random.randn(1000, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
pdf = pdf.cumsum()
plt.figure(); pdf.plot(); plt.legend(loc='best')